version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    command: uvicorn main:app --host "0.0.0.0" --port "8000" --reload
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12.4-alpine
